### ISSUE TITLE
void api calls throws IllegalStateException

### ISSUE THREAD

**Issue by Scrier** [morimekta/providence#99] opened 2018-02-05 12:00 UTC
Exception:
```
java.lang.IllegalStateException: No union field set in email_api.EmailService.sendEmail.response
	at net.zedge.email.api.EmailService$_sendEmail_response.unionField(EmailService.java:959)
	at net.zedge.email.api.EmailService$Client.sendEmail(EmailService.java:85)
	at net.zedge.backend.supervisor.mail.UserMailImpl$EmailExecutor.send(UserMailImpl.java:106)
	at net.zedge.backend.supervisor.mail.UserMailImpl.send(UserMailImpl.java:68)
	at net.zedge.backend.supervisor.tasks.scheduled.IllegalSendMail.execute(IllegalSendMail.java:99)
	at net.zedge.backend.supervisor.tasks.scheduled.IllegalSendMail.execute(IllegalSendMail.java:52)
	at net.zedge.backend.supervisor.tasks.scheduled.BaseScheduledTask.lambda$run$0(BaseScheduledTask.java:37)
	at net.zedge.backend.supervisor.tasks.TaskResult.measure(TaskResult.java:30)
	at net.zedge.backend.supervisor.tasks.scheduled.BaseScheduledTask.run(BaseScheduledTask.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Thrift File:
```
service EmailService  {

    /**
     * Send a regular email
     *
     * @param GenericEmailRequest request
     *
     * @throws api.BadRequestException
     * @throws api.InternalErrorException
     */
    void sendEmail(1: GenericEmailRequest request)
        throws (
            1: api.BadRequestException ex1,
            2: api.InternalErrorException ex2,
        );
```

Generated Source (row 85 in email service):

   ```
         net.zedge.email.api.EmailService._sendEmail_response msg = (net.zedge.email.api.EmailService._sendEmail_response) resp.getMessage();
            if (msg.unionField() != null) {
                switch (msg.unionField()) {
                    case EX1:
                        throw msg.getEx1();
                    case EX2:
                        throw msg.getEx2();
                    case SUCCESS:
                        return;
                }
            }
```

Generated Source 2 (row 959 in email service):
```
        @Override
        @javax.annotation.Nonnull
        public _Field unionField() {
            if (tUnionField == null) throw new IllegalStateException("No union field set in email_api.EmailService.sendEmail.response");
            return tUnionField;
        }
```

**Comment by morimekta** [comment] 2018-02-05 12:15
This is a result of apache-thrift changing it's protocol. This is caused by providence being based on the protocol spec of 0.9.x, not 0.11.x. 0.10 accepted in essence both. And the change is sadly one I don't like, because it will cause void return methods accept response as if successful if the exception was not in the locally declared IDL.

E.g in old (client used IDL):
```thrift
service Test {
  void test() throws (1: MyFailure1);
}
```

And in new (server used IDL):
```thrift
service Test {
  void test() throws (1: MyFailure1 failure1, 2: MyFailure2 failure2);
}
```

If the server throws MyFailure2, then the client thinks the response was OK.

I will need to find a way to accept / produce apache thrift 0.11 compatible output, but will want to avoid a solution that removes this type of checking from providence. But the exception should have been a PApplicationException, not IllegalStateEception at least.

**Comment by morimekta** [comment] 2018-02-18 15:09
Split out #102 which takes care of the incompatibility problem. Closing this, as it is fixed.

**Closed by morimekta** 2018-02-18 15:09 UTC
Labels: bug
